import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { AppShell } from "@/components/AppShell";
import { Brain, Check, ChevronDown, ChevronRight, Search, X } from "lucide-react";

export const Route = createFileRoute("/_authenticated/mcqs")({
  component: McqsLibrary,
  head: () => ({
    meta: [
      { title: "MCQ Library · UNIE" },
      { name: "description", content: "Browse every UPSC-style MCQ generated from your newspaper articles." },
      { property: "og:title", content: "MCQ Library · UNIE" },
      { property: "og:description", content: "All AI-generated UPSC Prelims MCQs in one place." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
});

type Row = {
  id: string;
  article_id: string;
  question: string;
  options: string[];
  correct_index: number;
  explanation: string | null;
  difficulty: string | null;
  topic: string | null;
  created_at: string;
  articles: { title: string; subject: string | null; gs_paper: string | null } | null;
};

function McqsLibrary() {
  const [q, setQ] = useState("");
  const [difficulty, setDifficulty] = useState<string>("all");
  const [open, setOpen] = useState<Record<string, boolean>>({});

  const query = useQuery({
    queryKey: ["mcqs-library"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("mcqs")
        .select("id, article_id, question, options, correct_index, explanation, difficulty, topic, created_at, articles(title, subject, gs_paper)")
        .order("created_at", { ascending: false })
        .limit(500);
      if (error) throw error;
      return (data ?? []) as unknown as Row[];
    },
  });

  const filtered = useMemo(() => {
    const needle = q.trim().toLowerCase();
    return (query.data ?? []).filter((r) => {
      if (difficulty !== "all" && (r.difficulty ?? "").toLowerCase() !== difficulty) return false;
      if (!needle) return true;
      return (
        r.question.toLowerCase().includes(needle) ||
        (r.topic ?? "").toLowerCase().includes(needle) ||
        (r.articles?.title ?? "").toLowerCase().includes(needle)
      );
    });
  }, [query.data, q, difficulty]);

  return (
    <AppShell>
      <header className="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="font-serif text-3xl">MCQ Library</h1>
          <p className="text-sm text-muted-foreground">
            All UPSC-style MCQs generated by Groq + Gemini from your articles.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="relative">
            <Search className="pointer-events-none absolute left-2 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <input
              value={q}
              onChange={(e) => setQ(e.target.value)}
              placeholder="Search question, topic, article…"
              className="w-64 rounded-md border border-input bg-card py-1.5 pl-8 pr-2 text-sm"
            />
          </div>
          <select
            value={difficulty}
            onChange={(e) => setDifficulty(e.target.value)}
            className="rounded-md border border-input bg-card px-2 py-1.5 text-sm"
          >
            <option value="all">All difficulties</option>
            <option value="easy">Easy</option>
            <option value="medium">Medium</option>
            <option value="hard">Hard</option>
          </select>
        </div>
      </header>

      {query.isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
      {!query.isLoading && filtered.length === 0 && (
        <div className="rounded-md border border-dashed border-border p-8 text-center text-sm text-muted-foreground">
          No MCQs yet. Open any article and hit <span className="font-medium text-foreground">Generate MCQs</span>.
        </div>
      )}

      <ol className="space-y-3">
        {filtered.map((m, idx) => {
          const isOpen = open[m.id] ?? false;
          return (
            <li key={m.id} className="rounded-md border border-border bg-card">
              <button
                onClick={() => setOpen((o) => ({ ...o, [m.id]: !isOpen }))}
                className="flex w-full items-start gap-3 px-4 py-3 text-left"
              >
                {isOpen ? (
                  <ChevronDown className="mt-1 h-4 w-4 text-muted-foreground" />
                ) : (
                  <ChevronRight className="mt-1 h-4 w-4 text-muted-foreground" />
                )}
                <div className="flex-1">
                  <div className="mb-1 flex flex-wrap items-center gap-2 text-[10px] uppercase tracking-wide text-muted-foreground">
                    <span className="rounded bg-secondary px-1.5 py-0.5 text-secondary-foreground">Q{idx + 1}</span>
                    {m.difficulty && (
                      <span className="rounded bg-secondary px-1.5 py-0.5 text-secondary-foreground">
                        {m.difficulty}
                      </span>
                    )}
                    {m.topic && <span className="text-muted-foreground">{m.topic}</span>}
                    {m.articles?.gs_paper && (
                      <span className="rounded bg-primary/10 px-1.5 py-0.5 text-primary">{m.articles.gs_paper}</span>
                    )}
                  </div>
                  <p className="text-sm font-medium leading-snug">{m.question}</p>
                  {m.articles && (
                    <Link
                      to="/articles/$articleId"
                      params={{ articleId: m.article_id }}
                      onClick={(e) => e.stopPropagation()}
                      className="mt-1 inline-block text-xs text-muted-foreground hover:text-foreground"
                    >
                      From: {m.articles.title}
                    </Link>
                  )}
                </div>
                <Brain className="mt-1 h-4 w-4 text-accent" />
              </button>

              {isOpen && (
                <div className="border-t border-border px-4 py-3">
                  <ul className="grid gap-1.5">
                    {m.options.map((opt, i) => {
                      const correct = i === m.correct_index;
                      return (
                        <li
                          key={i}
                          className={
                            "flex items-start gap-2 rounded border px-3 py-2 text-sm " +
                            (correct
                              ? "border-emerald-500/60 bg-emerald-500/10"
                              : "border-input")
                          }
                        >
                          <span className="mt-0.5 w-4 text-xs font-semibold text-muted-foreground">
                            {String.fromCharCode(65 + i)}
                          </span>
                          <span className="flex-1">{opt}</span>
                          {correct ? (
                            <Check className="h-4 w-4 text-emerald-600" />
                          ) : (
                            <X className="h-4 w-4 text-muted-foreground/40" />
                          )}
                        </li>
                      );
                    })}
                  </ul>
                  {m.explanation && (
                    <div className="mt-3 rounded border-l-2 border-accent bg-background p-3 text-sm">
                      <p className="text-[11px] uppercase tracking-wide text-accent">Explanation</p>
                      <p className="mt-1 leading-relaxed">{m.explanation}</p>
                    </div>
                  )}
                </div>
              )}
            </li>
          );
        })}
      </ol>
    </AppShell>
  );
}
