/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedArticlesRouteImport } from './routes/_authenticated/articles'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedMcqsRouteImport } from './routes/_authenticated/mcqs'
import { Route as AuthenticatedNcertRouteImport } from './routes/_authenticated/ncert'
import { Route as AuthenticatedPibRouteImport } from './routes/_authenticated/pib'
import { Route as AuthenticatedSetsRouteImport } from './routes/_authenticated/sets'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedArticlesArticleIdRouteImport } from './routes/_authenticated/articles.$articleId'
import { Route as AuthenticatedPlaygroundNewspaperIdRouteImport } from './routes/_authenticated/playground.$newspaperId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArticlesRoute = AuthenticatedArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMcqsRoute = AuthenticatedMcqsRouteImport.update({
  id: '/mcqs',
  path: '/mcqs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNcertRoute = AuthenticatedNcertRouteImport.update({
  id: '/ncert',
  path: '/ncert',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPibRoute = AuthenticatedPibRouteImport.update({
  id: '/pib',
  path: '/pib',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetsRoute = AuthenticatedSetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArticlesArticleIdRoute =
  AuthenticatedArticlesArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AuthenticatedArticlesRoute,
  } as any)
const AuthenticatedPlaygroundNewspaperIdRoute =
  AuthenticatedPlaygroundNewspaperIdRouteImport.update({
    id: '/playground/$newspaperId',
    path: '/playground/$newspaperId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/articles': typeof AuthenticatedArticlesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/mcqs': typeof AuthenticatedMcqsRoute
  '/ncert': typeof AuthenticatedNcertRoute
  '/pib': typeof AuthenticatedPibRoute
  '/sets': typeof AuthenticatedSetsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/articles/$articleId': typeof AuthenticatedArticlesArticleIdRoute
  '/playground/$newspaperId': typeof AuthenticatedPlaygroundNewspaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/articles': typeof AuthenticatedArticlesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/mcqs': typeof AuthenticatedMcqsRoute
  '/ncert': typeof AuthenticatedNcertRoute
  '/pib': typeof AuthenticatedPibRoute
  '/sets': typeof AuthenticatedSetsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/articles/$articleId': typeof AuthenticatedArticlesArticleIdRoute
  '/playground/$newspaperId': typeof AuthenticatedPlaygroundNewspaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/articles': typeof AuthenticatedArticlesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/mcqs': typeof AuthenticatedMcqsRoute
  '/_authenticated/ncert': typeof AuthenticatedNcertRoute
  '/_authenticated/pib': typeof AuthenticatedPibRoute
  '/_authenticated/sets': typeof AuthenticatedSetsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/articles/$articleId': typeof AuthenticatedArticlesArticleIdRoute
  '/_authenticated/playground/$newspaperId': typeof AuthenticatedPlaygroundNewspaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/articles'
    | '/dashboard'
    | '/history'
    | '/mcqs'
    | '/ncert'
    | '/pib'
    | '/sets'
    | '/upload'
    | '/articles/$articleId'
    | '/playground/$newspaperId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/articles'
    | '/dashboard'
    | '/history'
    | '/mcqs'
    | '/ncert'
    | '/pib'
    | '/sets'
    | '/upload'
    | '/articles/$articleId'
    | '/playground/$newspaperId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/articles'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/mcqs'
    | '/_authenticated/ncert'
    | '/_authenticated/pib'
    | '/_authenticated/sets'
    | '/_authenticated/upload'
    | '/_authenticated/articles/$articleId'
    | '/_authenticated/playground/$newspaperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles': {
      id: '/_authenticated/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedArticlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcqs': {
      id: '/_authenticated/mcqs'
      path: '/mcqs'
      fullPath: '/mcqs'
      preLoaderRoute: typeof AuthenticatedMcqsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ncert': {
      id: '/_authenticated/ncert'
      path: '/ncert'
      fullPath: '/ncert'
      preLoaderRoute: typeof AuthenticatedNcertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pib': {
      id: '/_authenticated/pib'
      path: '/pib'
      fullPath: '/pib'
      preLoaderRoute: typeof AuthenticatedPibRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sets': {
      id: '/_authenticated/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof AuthenticatedSetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/$articleId': {
      id: '/_authenticated/articles/$articleId'
      path: '/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof AuthenticatedArticlesArticleIdRouteImport
      parentRoute: typeof AuthenticatedArticlesRoute
    }
    '/_authenticated/playground/$newspaperId': {
      id: '/_authenticated/playground/$newspaperId'
      path: '/playground/$newspaperId'
      fullPath: '/playground/$newspaperId'
      preLoaderRoute: typeof AuthenticatedPlaygroundNewspaperIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedArticlesRouteChildren {
  AuthenticatedArticlesArticleIdRoute: typeof AuthenticatedArticlesArticleIdRoute
}

const AuthenticatedArticlesRouteChildren: AuthenticatedArticlesRouteChildren = {
  AuthenticatedArticlesArticleIdRoute: AuthenticatedArticlesArticleIdRoute,
}

const AuthenticatedArticlesRouteWithChildren =
  AuthenticatedArticlesRoute._addFileChildren(
    AuthenticatedArticlesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedArticlesRoute: typeof AuthenticatedArticlesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMcqsRoute: typeof AuthenticatedMcqsRoute
  AuthenticatedNcertRoute: typeof AuthenticatedNcertRoute
  AuthenticatedPibRoute: typeof AuthenticatedPibRoute
  AuthenticatedSetsRoute: typeof AuthenticatedSetsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedPlaygroundNewspaperIdRoute: typeof AuthenticatedPlaygroundNewspaperIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedArticlesRoute: AuthenticatedArticlesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMcqsRoute: AuthenticatedMcqsRoute,
  AuthenticatedNcertRoute: AuthenticatedNcertRoute,
  AuthenticatedPibRoute: AuthenticatedPibRoute,
  AuthenticatedSetsRoute: AuthenticatedSetsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedPlaygroundNewspaperIdRoute:
    AuthenticatedPlaygroundNewspaperIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
